name: Express.js CD
on:

  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: alcap1990
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.18"

      - name: Installing Dependencies
        run: npm i

      - name: testing our app
        run: npm test

  deploy:
    needs: [test]
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:  
      - name: call render webhook 
        uses: fjogeleit/http-request-action@v1 
        with:
          url: ${{ secrets.RENDER_HOOK }}
          method: 'GET'